
import { GoogleGenAI, Modality } from "@google/genai";
import type { GenerateContentResponse } from "@google/genai";

export const generateThumbnail = async (title: string, imageBase64: string, mimeType: string): Promise<string> => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const prompt = `
    Create a professional, scroll-stopping YouTube video thumbnail with a 16:9 aspect ratio (1280x720 pixels).

    **Video Title:** "${title}"

    **Instructions:**
    1.  Use the provided headshot image as the central subject. The person in the image is the YouTuber.
    2.  Modify the YouTuber's facial expression to realistically match the tone and emotion of the video title (e.g., excitement, shock, curiosity, seriousness). Do not make it look like a caricature. Keep it realistic.
    3.  Design a visually stunning background that complements the video title. Use high-contrast, vibrant colors and cinematic depth of field (blurry background) to make the subject pop.
    4.  Add glowing highlights and dramatic lighting to the subject and key elements to create a dynamic and engaging look.
    5.  Incorporate the video title text onto the thumbnail. Use a bold, modern, and highly readable font. The text placement should be strategic, eye-catching, and not obscure the YouTuber's face.
    6.  The final image must look like it was made by a professional YouTube designer, fully optimized for a high click-through rate. It must be polished and high-quality.
    `;

    const response: GenerateContentResponse = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: imageBase64,
                        mimeType: mimeType,
                    },
                },
                {
                    text: prompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error("No image was generated by the API.");
};
